#!/usr/bin/env python3
"""voice.py <remotion-project> [--only id,id] [--engine E] [--voice V] [--speed S] [--rate R]

Builds a Remotion project's narration from its script of record, <project>/narration.json:
  {"tts": {...}, "sections": [{"id": "scan", "audio": "sy_scan.mp3", "text": "..."}]}
For every section it lints the text (errors stop the run), voices it sentence by sentence
(tts_engines.py), loudness-normalizes to -17 LUFS, writes public/audio/<audio>, and records
the exact duration and each sentence's start. Timing lands in narration.timing.json and in
src/narration.gen.ts, which the template's specs read:
  audioDur: NARRATION.scan.dur,  focalAt: cue('scan', 1)   // sentence 1 starts
Voice settings: --flags > narration.json "tts" > the brand profile's "tts" > edge-tts with
the profile's voice/rate. Voiced sentences are cached in <project>/.tts-cache, so editing
one sentence re-voices only that sentence.
"""
import argparse, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)


def resolve_tts(narr, profile, cli):
    base = narr.get("tts") or profile.get("tts") or {
        "engine": "edge", "voice": profile.get("voice", "en-US-AvaNeural"), "rate": profile.get("rate", "+0%")}
    return {**base, **{k: v for k, v in cli.items() if v is not None}}


def gen_ts(timing):
    rows = "\n".join(f'  "{k}": {json.dumps(timing[k], separators=(", ", ": "))},' for k in sorted(timing))
    return ("// Generated by the toolkit's scripts/voice.py from narration.json. Do not edit by hand.\n"
            "export type Narration = { dur: number; starts: number[]; durs: number[] };\n"
            "export const NARRATION: Record<string, Narration> = {\n" + rows + "\n};\n\n"
            "// Seconds into a section's voiceover where sentence n starts, plus frac of that sentence.\n"
            "export const cue = (id: string, n: number, frac = 0): number => {\n"
            "  const s = NARRATION[id];\n"
            "  if (!s || n >= s.starts.length) throw new Error(`no sentence ${n} in narration '${id}'`);\n"
            "  return s.starts[n] + frac * s.durs[n];\n"
            "};\n")


def _dur(path):
    return round(float(subprocess.check_output(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                                                "-of", "csv=p=0", path], stdin=subprocess.DEVNULL).decode()), 3)


def main():
    from brand_config import load_profile
    from narration_lint import lint
    from pronounce import load_map
    from tts_engines import speak

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("project")
    ap.add_argument("--only", help="comma-separated section ids")
    for flag in ("engine", "voice", "rate"):
        ap.add_argument(f"--{flag}")
    ap.add_argument("--speed", type=float)
    a = ap.parse_args()

    narr = json.load(open(os.path.join(a.project, "narration.json"), encoding="utf-8"))
    profile = load_profile(narr.get("brand"))
    tts = resolve_tts(narr, profile, {"engine": a.engine, "voice": a.voice, "rate": a.rate, "speed": a.speed})
    pmap = load_map(brand=narr.get("brand"))
    only = set(a.only.split(",")) if a.only else None
    timing_path = os.path.join(a.project, "narration.timing.json")
    timing = json.load(open(timing_path, encoding="utf-8")) if os.path.exists(timing_path) else {}
    cache = os.path.join(a.project, ".tts-cache")
    os.makedirs(os.path.join(a.project, "public", "audio"), exist_ok=True)

    sections = [s for s in narr["sections"] if not only or s["id"] in only]
    errors = 0
    for s in sections:
        for level, msg in lint(s["text"]):
            print(f"{s['id']}: {level}: {msg}")
            errors += level == "error"
    if errors:
        sys.exit(f"{errors} lint error(s): fix the script before voicing it")

    for s in sections:
        wav = os.path.join(cache, f"_section_{s['id']}.wav")
        r = speak(s["text"], wav, tts, pmap, cache)
        mp3 = os.path.join(a.project, "public", "audio", s["audio"])
        subprocess.run(["ffmpeg", "-nostdin", "-v", "error", "-i", wav, "-af", "loudnorm=I=-17:TP=-2:LRA=11",
                        "-ar", "48000", "-ac", "2", "-b:a", "192k", "-y", mp3], check=True)
        timing[s["id"]] = {"dur": _dur(mp3), "starts": r["starts"], "durs": r["durs"]}
        print(f"{s['id']:12s} {timing[s['id']]['dur']:6.2f}s  {len(r['starts'])} sentences -> public/audio/{s['audio']}")

    with open(timing_path, "w", encoding="utf-8") as f:
        json.dump(timing, f, indent=1, sort_keys=True)
    with open(os.path.join(a.project, "src", "narration.gen.ts"), "w", encoding="utf-8", newline="\n") as f:
        f.write(gen_ts(timing))
    print(f"voiced {len(sections)} section(s) with {tts.get('engine', 'edge')} {tts.get('voice', '')}; "
          f"wrote narration.timing.json and src/narration.gen.ts")


if __name__ == "__main__":
    main()
